name: oknoapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <3.10.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  video_player: ^2.7.0
  # get_it: ^7.6.0
  stacked: ^3.4.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  flutter_staggered_animations: ^1.1.1
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  fluttertoast: ^8.2.2
  like_button: ^2.0.5
  flutter_custom_tabs: ^1.0.4
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  ionicons: ^0.2.2
  firebase_storage: ^11.2.5
  firebase_analytics: ^10.4.4
  firebase_dynamic_links: ^5.3.4
  share_plus: ^7.1.0
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.0
  readmore: ^2.2.0
  dio: ^5.3.2
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/OknoIcon.png"