name: oknoapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <3.10.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  video_player: ^2.7.0
  get_it: ^7.6.0
  stacked: ^3.4.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  flutter_staggered_animations: ^1.1.1
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  fluttertoast: ^8.2.2
  video_thumbnail: ^0.5.3
  like_button: ^2.0.5
  flutter_custom_tabs: ^1.0.4
  path_provider: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  camera: ^0.10.5+3
  image_picker: ^1.0.2
  ionicons: ^0.2.2
  firebase_storage: ^11.2.5
  firebase_analytics: ^10.4.4
  firebase_dynamic_links: ^5.3.4
  share_plus: ^7.1.0
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.0
  video_editor: ^3.0.0
  #yoyo_player: ^0.1.0
  cdnbye: ^1.3.0
  chewie: ^1.7.0
  helpers: ^1.2.3
  jiffy: ^6.2.1
  webview_flutter: ^4.2.2
  ffmpeg_kit_flutter_full_gpl: 5.1.0-LTS
  readmore: ^2.2.0
  flutter_video_info: ^1.3.1
  audioplayers: ^5.1.0
  dio: ^5.3.2
  filter_list: ^1.0.2
  lazy_load_scrollview: ^1.3.0
  tuple: ^2.0.2
  fraction: ^4.1.4
  #super_easy_permissions: ^0.1.1
  #permission_handler: ^8.2.5
  awesome_dialog: ^3.1.0
  firebase_messaging: ^14.6.5
  flutter_launcher_icons: ^0.9.2
  amplify_storage_s3: ^1.3.1
  amplify_auth_cognito: ^1.0.0
  
# dependency_overrides:
#   flutter_video_editor:
#     dependency:
#       com.arthenica.ffmpegkit:
#         excludes: com.arthenica.ffmpegkit.Abi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/OknoIcon.png"