class Autogenerated {
  late List<Likes> likes;

  Autogenerated({required this.likes});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['likes'] != null) {
      likes = <Likes>[];
      json['likes'].forEach((v) {
        likes.add(Likes.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['tags'] = likes.map((v) => v.toJson()).toList();
    return data;
  }
}

class Likes {
  late String likes;

  Likes({
    required this.likes,
  });

  Likes.fromJson(Map<String, dynamic> json) {
    likes = json['likes'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['likes'] = likes;
    return data;
  }
}
